/**
 * AddQuicktag Script to add listbox to visual-editor
 * 
 * @package  AddQuicktag Plugin
 * @author   Frank Bueltge <frank@bueltge.de>
 * @version  07/11/2012
 * @since    2.0.0
 */

jQuery(document).ready(function(a){if(typeof addquicktag_tags=="undefined")return;if(typeof addquicktag_post_type=="undefined")return;if(typeof addquicktag_pt_for_js=="undefined")return;if(-1==a.inArray(addquicktag_post_type,addquicktag_pt_for_js))return;var b=0;var c=0;for(i=0;i<addquicktag_tags.buttons.length;i++){if(1===parseInt(addquicktag_tags.buttons[i]["visual"]))b=addquicktag_tags.buttons[i]["visual"];if(1===parseInt(addquicktag_tags.buttons[i][addquicktag_post_type]))c=addquicktag_tags.buttons[i][addquicktag_post_type]}if(1!==parseInt(b))return;if(1!==parseInt(c))return;tinymce.PluginManager.requireLangPack("rmnlQuicktagSettings_tmce");tinymce.create("tinymce.plugins.AddQuicktag",{createControl:function(a,b){switch(a){case"rmnlQuicktagSettings_tmce":var c=addquicktag_tags["buttons"],d=0,e="",f=b.createListBox("rmnlQuicktagSettings_tmce",{title:"Quicktags",onselect:function(a){var b=tinyMCE.activeEditor.selection.getContent(),d=true;switch(a){case"null":d=false;break;default:break}if(d==true){if(typeof c[a].end=="undefined")c[a].end="";tinyMCE.activeEditor.selection.setContent(c[a].start+b+c[a].end)}}});if(typeof c!=="undefined"){for(d=0;d<c.length;d++){if(1===parseInt(c[d][addquicktag_post_type])){if(1==c[d].visual)f.add(c[d].text,String(d))}}}else{f.add("rmnlQuicktagSettings_tmce.addquicktag_select_error","null")}return f;break}return null},getInfo:function(){return{longname:"AddQuicktag Plugin for TinyMCE in WordPress",author:"Frank Bueltge",authorurl:"http://bueltge.de/",infourl:"http://wordpress.org/extend/plugins/addquicktag/",version:tinymce.majorVersion+"."+tinymce.minorVersion}}});tinymce.PluginManager.add("rmnlQuicktagSettings_tmce",tinymce.plugins.AddQuicktag)})